### ISSUE TITLE
Clean up readme.txt for Plugin Update Checker

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-docraptor#20]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-docraptor/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-docraptor) to see if your bug or enhancement is already listed?

### Description

See #19 and https://github.com/pressbooks/pressbooks/pull/954.

### Steps to Reproduce

Not applicable.

### System Information

DocRaptor for Pressbooks: dev-dev

**Comment by dac514** [comment]
![explainor](https://user-images.githubusercontent.com/812192/30921269-0d3c5f42-a374-11e7-8c76-ac7452f6da1d.PNG)


Did some minor cleanup using https://wordpress.org/plugins/developers/readme-validator/
Some complaints, but nothing serious. Parses fine.
