### ISSUE TITLE
Plugin Conflict issue 

### ISSUE THREAD

**Issue by johnpeterm** [pressbooks/pressbooks-docraptor#26]
### Prerequisites
Pressbook Version 5.4.5
Wordrepress version  4.9.8

Installed pressbooks-docraptor and network enabled, then the complete website and admin panel goes blank and error message "unable to reach the website".

Composer and other requisite dependencies installed in the server. 

I feel since docraptor not tested with current version, there might be conflict issue. Appreciate update on this.

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks and this plugin deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [this plugin](http://github.com/pressbooks/pressbooks-docraptor/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-docraptor) to see if your bug or enhancement is already listed?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### System Information

_Replace this section with the contents of the Diagnostics page, available at `https://<yourdomain.tld>/<yourbook>/wp-admin/options.php?page=pressbooks_diagnostics` or via the Diagnostics link in the admin footer._

**Comment by greatislander** [comment]
In Pressbooks 5.4, we moved the functionality from this plugin into the Pressbooks plugin. See: https://github.com/pressbooks/pressbooks/issues/1238

You should not install this plugin if you are running Pressbooks >= 5.4.
